services:
    gitea:
        image: docker.gitea.com/gitea:1.26.4
        environment:
            - USER_UID=${PUID}
            - USER_GID=${PGID}
            - TZ=${TZ}
        ports:
            - ${GITEA_SSH_PORT}:22
        volumes:
            - ${APPDATA}/gitea:/data
            - /etc/localtime:/etc/localtime:ro
        networks:
            - core_net
        healthcheck:
            test: ["CMD", "curl", "-fSs", "http://127.0.0.1:3000"]
            interval: 60s
            timeout: 10s
            retries: 20
            start_period: 15s
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
            placement:
                constraints:
                    - node.role == manager

networks:
    core_net:
        external: true