when:
  - event: push
    branch: main
  - event: manual
    branch: main

skip_clone: true

steps:
  apprise-alert:
    image: curlimages/curl:latest
    directory: /tmp
    environment:
      APPRISE_ENDPOINT_URL:
        from_secret: apprise_url
    commands:
      - |
        MSG="Pipeline #$CI_PIPELINE_NUMBER status is $CI_PIPELINE_STATUS for $CI_REPO"
        
        curl -X POST "$APPRISE_ENDPOINT_URL" \
          -H "Content-Type: application/json" \
          -d "{
            \"title\": \"Woodpecker CI Build Alert\",
            \"body\": \"$MSG\",
            \"type\": \"$CI_PIPELINE_STATUS\"
          }"
    when:
      status: [ success, failure ]

