when:
  - event: push
    branch: main
  - event: manual
    branch: main

skip_clone: true

steps:
  apprise-alert:
    image: curlimages/curl:latest
    secrets: [ apprise_url ]
    commands:
      - |
        # Format the notification body text
        MSG="Pipeline #$CI_PIPELINE_NUMBER status is $CI_PIPELINE_STATUS for $CI_REPO"
        
        # Send payload to the injected secret URL variable
        curl -X POST "$APPRISE_ENDPOINT_URL" \
          -H "Content-Type: application/json" \
          -d "{
            \"title\": \"Woodpecker CI Build Alert\",
            \"body\": \"$MSG\",
            \"type\": \"$CI_PIPELINE_STATUS\"
          }"
    when:
      status: [ success, failure ]
